#ifndef ASR_CORE_UTILS_STDEXECUTION_H
#define ASR_CORE_UTILS_STDEXECUTION_H

#include <AutoStarRail/AsrConfig.h>

ASR_DISABLE_WARNING_BEGIN
ASR_IGNORE_UNUSED_PARAMETER

#include <stdexec/execution.hpp>

ASR_DISABLE_WARNING_END

#endif // ASR_CORE_UTILS_STDEXECUTION_H
