#ifndef DAS_CORE_FOREIGNINTERFACEHOST_FOREIGNINTERFACEHOSTENUM_H
#define DAS_CORE_FOREIGNINTERFACEHOST_FOREIGNINTERFACEHOSTENUM_H

#include <das/Core/ForeignInterfaceHost/Config.h>

DAS_CORE_FOREIGNINTERFACEHOST_NS_BEGIN

enum class ForeignInterfaceLanguage
{
    Python,
    CSharp,
    Java,
    Cpp,
    Lua,
    Node
};

enum class LoadMode
{
    InProcess,
    Ipc
};

DAS_CORE_FOREIGNINTERFACEHOST_NS_END

#endif // DAS_CORE_FOREIGNINTERFACEHOST_FOREIGNINTERFACEHOSTENUM_H
