#ifndef DAS_CORE_FOREIGNINTERFACEHOST_IDASINPUTMANAGERIMPL_H
#define DAS_CORE_FOREIGNINTERFACEHOST_IDASINPUTMANAGERIMPL_H

#include <das/Core/ForeignInterfaceHost/Config.h>
#include <DAS/_autogen/idl/abi/IDasInputManager.h>

DAS_CORE_FOREIGNINTERFACEHOST_NS_BEGIN

DAS_CORE_FOREIGNINTERFACEHOST_NS_END

#endif // DAS_CORE_FOREIGNINTERFACEHOST_IDASINPUTMANAGERIMPL_H
