#!/usr/bin/env python3
"""
IPC Messages 聚合脚本

用法:
    python aggregate_messages.py --ipc-output-dir <dir> [--output-file <filename>]

示例:
    python aggregate_messages.py --ipc-output-dir C:/vmbuild/das/include/das/_autogen/idl/ipc
    python aggregate_messages.py --ipc-output-dir ./ipc --output-file AllMessages.h

功能:
    从 messages/ 子目录下的所有 *Messages.h 文件生成一个汇总的 AllMessages.h 文件
"""

import argparse
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import List


def aggregate_messages(ipc_output_dir: Path, output_filename: str = "AllMessages.h") -> int:
    """
    从所有 *Messages.h 文件汇总生成 AllMessages.h
    
    Args:
        ipc_output_dir: IPC 输出目录（包含 messages/ 子目录）
        output_filename: 输出文件名，默认为 AllMessages.h
    
    Returns:
        0 表示成功，非0 表示失败
    """
    messages_dir = ipc_output_dir / "messages"
    
    if not messages_dir.exists():
        print(f"Messages directory does not exist: {messages_dir}")
        return 0  # 没有目录也是成功的
    
    # 查找所有 *Messages.h 文件
    message_files = sorted(messages_dir.glob("*Messages.h"))
    
    if not message_files:
        print(f"No *Messages.h files found in {messages_dir}")
        return 0  # 没有文件也是成功的
    
    print(f"Found {len(message_files)} Messages.h files")
    
    # 生成汇总文件
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    
    lines = []
    lines.append("#if !defined(DAS_IPC_ALL_MESSAGES_H)")
    lines.append("#define DAS_IPC_ALL_MESSAGES_H")
    lines.append("")
    lines.append("// This file is automatically generated by DAS IDL Message Aggregator")
    lines.append(f"// Generated at: {timestamp}")
    lines.append("// !!! DO NOT EDIT !!!")
    lines.append("//")
    lines.append("// Master IPC messages header - includes all generated message structures")
    lines.append("//")
    lines.append("")
    
    # 按文件名排序包含
    for msg_file in message_files:
        filename = msg_file.name
        lines.append(f'#include "messages/{filename}"')
    
    lines.append("")
    lines.append("#endif // DAS_IPC_ALL_MESSAGES_H")
    lines.append("")
    
    # 写入汇总文件
    output_path = ipc_output_dir / output_filename
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))
    
    print(f"Generated {output_filename}: {output_path}")
    
    return 0


def main():
    parser = argparse.ArgumentParser(
        description='Aggregate IPC messages from *Messages.h files',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例:
  %(prog)s --ipc-output-dir C:/vmbuild/das/include/das/_autogen/idl/ipc
  %(prog)s --ipc-output-dir ./ipc --output-file AllMessages.h
"""
    )
    
    parser.add_argument(
        '--ipc-output-dir',
        required=True,
        help='IPC 输出目录（包含 messages/ 子目录）'
    )
    
    parser.add_argument(
        '--output-file',
        default='AllMessages.h',
        help='输出文件名（默认: AllMessages.h）'
    )
    
    args = parser.parse_args()
    
    ipc_output_dir = Path(args.ipc_output_dir)
    
    if not ipc_output_dir.exists():
        print(f"Error: Directory does not exist: {ipc_output_dir}", file=sys.stderr)
        return 1
    
    if not ipc_output_dir.is_dir():
        print(f"Error: Not a directory: {ipc_output_dir}", file=sys.stderr)
        return 1
    
    return aggregate_messages(ipc_output_dir, args.output_file)


if __name__ == '__main__':
    sys.exit(main())
