#!/usr/bin/env python3
"""
IPC Proxy/Stub 聚合脚本

生成汇总文件，让生成的 .h 代码能被编译：
- IpcAllProxies.h  (include 所有 proxy/*Proxy.h)
- IpcAllStubs.h    (include 所有 stub/*Stub.h)
- IpcGenerated.cpp (include 上面两个头文件)
- IpcProxyFactory.h (包含所有 proxy 的 CreateProxyByInterfaceId switch-case)
- IpcStubFactory.h (包含所有 stub 的 RegisterHandler 调用)

用法:
    python aggregate_ipc.py --ipc-output-dir <dir> [--ipc-cache-dir <dir>]
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Any

from ipc_common import BUILTIN_INTERFACE_HASHES

# 匹配时间戳注释行，比较内容时忽略这些行
_TIMESTAMP_PATTERN = re.compile(r'^//\s*(?:Auto-)?[Gg]enerated (?:at|by DAS IDL Aggregator).*$', re.MULTILINE)


def _write_if_changed(file_path: Path, content: str) -> bool:
    """仅当内容（忽略时间戳行）发生变化时才写入文件。返回 True 表示文件已更新。"""
    if file_path.exists():
        try:
            existing = file_path.read_text(encoding='utf-8')
            # 比较时忽略时间戳行
            if _TIMESTAMP_PATTERN.sub('', existing) == _TIMESTAMP_PATTERN.sub('', content):
                return False
        except Exception:
            pass
    file_path.write_text(content, encoding='utf-8')
    return True


def _get_interface_short_name(interface_name: str) -> str:
    """Strip I prefix from interface name: IDasPluginPackage -> DasPluginPackage"""
    if interface_name.startswith('IDas'):
        return interface_name[1:]
    if interface_name.startswith('I') and len(interface_name) > 1:
        return interface_name[1:]
    return interface_name


def aggregate_ipc(ipc_output_dir: Path, ipc_cache_dir: Path = None) -> int:
    """
    生成 IPC 汇总文件

    Args:
        ipc_output_dir: IPC 输出目录
        ipc_cache_dir: IPC 缓存目录（包含 per-interface JSON 文件）
    """
    proxy_dir = ipc_output_dir / "proxy"
    stub_dir = ipc_output_dir / "stub"

    # 查找所有 Proxy 和 Stub 文件
    proxy_files = sorted(proxy_dir.glob("*Proxy.h")) if proxy_dir.exists() else []
    stub_files = sorted(stub_dir.glob("*Stub.h")) if stub_dir.exists() else []

    if not proxy_files and not stub_files:
        print("No Proxy or Stub files found")
        return 0

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    # 生成 IpcAllProxies.h
    if proxy_files:
        lines = [
            "#if !defined(DAS_IPC_ALL_PROXIES_H)",
            "#define DAS_IPC_ALL_PROXIES_H",
            "",
            f"// Auto-generated at: {timestamp}",
            "// !!! DO NOT EDIT !!!",
            "",
        ]
        for f in proxy_files:
            lines.append(f'#include "proxy/{f.name}"')
        lines.extend(["", "#endif // DAS_IPC_ALL_PROXIES_H", ""])

        content = "\n".join(lines)
        if _write_if_changed(ipc_output_dir / "IpcAllProxies.h", content):
            print(f"Generated IpcAllProxies.h ({len(proxy_files)} proxies)")

    # 生成 IpcAllStubs.h
    if stub_files:
        lines = [
            "#if !defined(DAS_IPC_ALL_STUBS_H)",
            "#define DAS_IPC_ALL_STUBS_H",
            "",
            f"// Auto-generated at: {timestamp}",
            "// !!! DO NOT EDIT !!!",
            "",
        ]
        for f in stub_files:
            lines.append(f'#include "stub/{f.name}"')
        lines.extend(["", "#endif // DAS_IPC_ALL_STUBS_H", ""])

        content = "\n".join(lines)
        if _write_if_changed(ipc_output_dir / "IpcAllStubs.h", content):
            print(f"Generated IpcAllStubs.h ({len(stub_files)} stubs)")

    # 生成 IpcGenerated.cpp
    cpp_lines = [
        "// This file is automatically generated by DAS IDL Aggregator",
        f"// Generated at: {timestamp}",
        "// !!! DO NOT EDIT !!!",
        "//",
        "// IPC 代码编译入口 - include 所有生成的 Proxy 和 Stub 代码",
        "//",
        "",
    ]
    if proxy_files:
        cpp_lines.append('#include "IpcAllProxies.h"')
    if stub_files:
        cpp_lines.append('#include "IpcAllStubs.h"')

    # Factory 文件由 aggregate_factory_files() 生成，如果存在则 include
    if (ipc_output_dir / "IpcProxyFactory.h").exists():
        cpp_lines.append('#include "IpcProxyFactory.h"')
    if (ipc_output_dir / "IpcStubFactory.h").exists():
        cpp_lines.append('#include "IpcStubFactory.h"')
    cpp_lines.append("")

    content = "\n".join(cpp_lines)
    if _write_if_changed(ipc_output_dir / "IpcGenerated.cpp", content):
        print("Generated IpcGenerated.cpp")

    return 0


def aggregate_factory_files(ipc_output_dir: Path, ipc_cache_dir: Path) -> int:
    """
    从 per-interface JSON 文件聚合生成 IpcProxyFactory.h 和 IpcStubFactory.h

    Args:
        ipc_output_dir: IPC 输出目录
        ipc_cache_dir: 缓存目录（包含 per-interface *.json 文件）

    Returns:
        0 表示成功
    """
    if not ipc_cache_dir.exists():
        print(f"Warning: IPC cache directory does not exist: {ipc_cache_dir}")
        return 0

    # 查找所有 interface JSON 文件
    json_files = sorted(ipc_cache_dir.glob("*.json"))
    if not json_files:
        print("No interface JSON files found in cache directory")
        return 0

    # 读取所有接口元数据
    interfaces: List[Dict[str, Any]] = []
    for json_file in json_files:
        try:
            with open(json_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
                interfaces.append(data)
        except Exception as e:
            print(f"Warning: Failed to read {json_file}: {e}")

    if not interfaces:
        print("No valid interface JSON files found")
        return 0

    # 按 interface_name 排序以保持一致性
    interfaces.sort(key=lambda x: x.get('interface_name', ''))

    # 收集唯一的 namespace 用于生成 using namespace 声明
    namespaces: Dict[str, List[str]] = {}  # namespace -> [short_names]
    for iface in interfaces:
        ns = iface.get('namespace', '')
        short_name = _get_interface_short_name(iface.get('interface_name', ''))
        if ns:
            if ns not in namespaces:
                namespaces[ns] = []
            namespaces[ns].append(short_name)

    # 生成 IpcProxyFactory.h
    _generate_proxy_factory(ipc_output_dir, interfaces, namespaces)

    # 生成 IpcStubFactory.h
    _generate_stub_factory(ipc_output_dir, interfaces, namespaces)

    return 0


def _generate_proxy_factory(ipc_output_dir: Path, interfaces: List[Dict[str, Any]],
                            namespaces: Dict[str, List[str]]) -> None:
    """生成 IpcProxyFactory.h"""

    # 收集所有 proxy 头文件
    proxy_files = sorted((ipc_output_dir / "proxy").glob("*Proxy.h")) if (ipc_output_dir / "proxy").exists() else []

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        "#if !defined(DAS_IPC_PROXY_FACTORY_H)",
        "#define DAS_IPC_PROXY_FACTORY_H",
        "",
        f"// Auto-generated at: {timestamp}",
        "// !!! DO NOT EDIT !!!",
        "",
        "#include <das/Core/IPC/IPCProxyBase.h>",
        "#include <das/Core/IPC/DasProxyBase.h>",
        "#include <das/IDasBase.h>",
        "#include <das/Core/IPC/ObjectId.h>",
        "#include <das/Core/IPC/IpcRunLoop.h>",
        "#include <das/Core/IPC/ProxyFactory.h>",
        "#include <atomic>",
        "#include <memory>",
        "#include <functional>",
        "#include <das/Core/IPC/RemoteObjectRegistry.h>",
        "",
    ]

    # Include all proxy headers
    for f in proxy_files:
        lines.append(f'#include "proxy/{f.name}"')

    lines.extend([
        "",
        "DAS_CORE_IPC_NS_BEGIN",
        "namespace DasIpcProxy {",
        "",
    ])

    # 添加 namespace using 声明
    for ns, short_names in sorted(namespaces.items()):
        lines.append(f"using namespace {ns}::IPC::Proxy;")

    if namespaces:
        lines.append("")

    # DasBaseProxy: minimal proxy for IDasBase, must be defined before CreateTypedProxy
    lines.extend([
        "// Minimal proxy for IDasBase - only supports AddRef/Release/QueryInterface",
        "// QueryInterface delegates to QueryInterfaceRemote (remote QI over IPC)",
        "// AddRef/Release: satisfy IDasBase pure virtual, delegate to DasProxyBase",
        "class DasBaseProxy : public DasProxyBase<IDasBase>, public IDasBase",
        "{",
        "public:",
        "    DasBaseProxy(",
        "        const ObjectId& object_id,",
        "        IpcRunLoop& run_loop,",
        "        std::weak_ptr<BusinessThread> business_thread,",
        "        ProxyFactory& proxy_factory)",
        "        : DasProxyBase<IDasBase>(",
        "              RemoteObjectRegistry::ComputeInterfaceId(DAS_IID_BASE),",
        "              object_id, run_loop, std::move(business_thread), proxy_factory)",
        "    {",
        "    }",
        "",
        "    uint32_t AddRef() final { return DasProxyBase<IDasBase>::AddRef(); }",
        "    uint32_t Release() final { return DasProxyBase<IDasBase>::Release(); }",
        "",
        "    DasResult QueryInterface(const DasGuid& iid, void** pp_object) override",
        "    {",
        "        return QueryInterfaceRemote(iid, pp_object);",
        "    }",
        "",
        "};",
        "",
    ])

    lines.extend([
        "template <typename TProxy>",
        "IDasBase* CreateTypedProxy(",
        "    const ObjectId& object_id,",
        "    IpcRunLoop& run_loop,",
        "    std::weak_ptr<BusinessThread> business_thread,",
        "    ProxyFactory& proxy_factory)",
        "{",
        "    return new TProxy(object_id, run_loop, std::move(business_thread), proxy_factory);",
        "}",
        "",
        "inline IDasBase* CreateProxyByInterfaceId(",
        "    uint32_t interface_id,",
        "    const ObjectId& object_id,",
        "    IpcRunLoop& run_loop,",
        "    std::weak_ptr<BusinessThread> business_thread,",
        "    ProxyFactory& proxy_factory)",
        "{",
        "    switch (interface_id) {",
    ])

    # 生成所有 case 分支
    for iface in interfaces:
        interface_name = iface.get('interface_name', '')
        interface_id = iface.get('interface_id', '0x00000000')
        short_name = _get_interface_short_name(interface_name)
        proxy_name = f"{short_name}Proxy"

        lines.append(f"        case {interface_id}: // {interface_name}::InterfaceId")
        lines.append(f"            return CreateTypedProxy<{proxy_name}>(object_id, run_loop, business_thread, proxy_factory);")

    das_base_hash = BUILTIN_INTERFACE_HASHES.get("IDasBase", 0)
    lines.extend([
        "        // IDasBase: minimal proxy that only supports remote QueryInterface",
        "        // AddRef/Release provided by DasProxyBase",
        f"        // interface_id = BUILTIN_INTERFACE_HASHES[\"IDasBase\"] = 0x{das_base_hash:08X}",
        f"        case 0x{das_base_hash:08X}u:",
        "            return CreateTypedProxy<DasBaseProxy>(object_id, run_loop, business_thread, proxy_factory);",
        "",
        "        default:",
        "            return nullptr;",
        "    }",
        "}",
        "",
        "} // namespace DasIpcProxy",
        "DAS_CORE_IPC_NS_END",
        "",
        "#endif // DAS_IPC_PROXY_FACTORY_H",
        "",
    ])

    content = "\n".join(lines)
    if _write_if_changed(ipc_output_dir / "IpcProxyFactory.h", content):
        print(f"Generated IpcProxyFactory.h ({len(interfaces)} proxies)")


def _generate_stub_factory(ipc_output_dir: Path, interfaces: List[Dict[str, Any]],
                           namespaces: Dict[str, List[str]]) -> None:
    """生成 IpcStubFactory.h"""

    # 收集所有 stub 头文件
    stub_files = sorted((ipc_output_dir / "stub").glob("*Stub.h")) if (ipc_output_dir / "stub").exists() else []

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        "#if !defined(DAS_IPC_STUB_FACTORY_H)",
        "#define DAS_IPC_STUB_FACTORY_H",
        "",
        f"// Auto-generated at: {timestamp}",
        "// !!! DO NOT EDIT !!!",
        "",
        "#include <das/Core/IPC/IStubBase.h>",
        "#include <das/Core/IPC/IpcRunLoop.h>",
        "#include <das/Core/IPC/IpcMessageHeader.h>",
        "",
    ]

    # Include all stub headers
    for f in stub_files:
        lines.append(f'#include "stub/{f.name}"')

    lines.extend([
        "",
        "namespace DasIpcStub {",
        "",
    ])

    # 添加 namespace using 声明
    for ns, short_names in sorted(namespaces.items()):
        lines.append(f"using namespace {ns}::IPC::Stub;")

    # 无命名空间的接口被放到 DasIpc::Stub，需要额外 using
    has_no_namespace = any(not iface.get('namespace', '') for iface in interfaces)
    if has_no_namespace:
        lines.append("using namespace DasIpc::Stub;")

    if namespaces:
        lines.append("")

    lines.extend([
        "struct StubFactory {",
        "    void RegisterAll(Das::Core::IPC::IpcRunLoop& run_loop) {",
    ])

    # 生成所有 RegisterHandler 调用
    for iface in interfaces:
        interface_name = iface.get('interface_name', '')
        interface_id = iface.get('interface_id', '0x00000000')
        short_name = _get_interface_short_name(interface_name)
        stub_name = f"{short_name}Stub"

        lines.append(f"        run_loop.RegisterHandler(Das::Core::IPC::HeaderFlags::NONE, {interface_id}, &{stub_name}_);")

    lines.extend([
        "    }",
        "",
    ])

    # 生成 stub 成员变量
    for iface in interfaces:
        interface_name = iface.get('interface_name', '')
        short_name = _get_interface_short_name(interface_name)
        stub_name = f"{short_name}Stub"
        lines.append(f"    [[no_unique_address]] {stub_name} {stub_name}_;")

    lines.extend([
        "};",
        "",
        "inline StubFactory g_stub_factory;",
        "",
        "} // namespace DasIpcStub",
        "",
        "#endif // DAS_IPC_STUB_FACTORY_H",
        "",
    ])

    content = "\n".join(lines)
    if _write_if_changed(ipc_output_dir / "IpcStubFactory.h", content):
        print(f"Generated IpcStubFactory.h ({len(interfaces)} stubs)")


def main():
    parser = argparse.ArgumentParser(description='Aggregate IPC Proxy/Stub files')
    parser.add_argument('--ipc-output-dir', required=True, help='IPC output directory')
    parser.add_argument('--ipc-cache-dir', help='IPC cache directory (contains per-interface JSON files)')
    args = parser.parse_args()

    ipc_output_dir = Path(args.ipc_output_dir)
    ipc_output_dir.mkdir(parents=True, exist_ok=True)

    ipc_cache_dir = Path(args.ipc_cache_dir) if args.ipc_cache_dir else None

    # 聚合工厂文件（IpcProxyFactory.h, IpcStubFactory.h）— 先执行
    if ipc_cache_dir:
        result = aggregate_factory_files(ipc_output_dir, ipc_cache_dir)
        if result != 0:
            return result

    # 聚合基础文件（IpcAllProxies.h, IpcAllStubs.h, IpcGenerated.cpp）— 后执行
    # IpcGenerated.cpp 会检测 factory 文件是否存在并 include
    result = aggregate_ipc(ipc_output_dir)
    if result != 0:
        return result

    return 0


if __name__ == '__main__':
    sys.exit(main())
