#!/usr/bin/env python3
"""
IPC Proxy/Stub 聚合脚本

生成汇总文件，让生成的 .h 代码能被编译：
- IpcAllProxies.h  (include 所有 proxy/*Proxy.h)
- IpcAllStubs.h    (include 所有 stub/*Stub.h)
- IpcGenerated.cpp (include 上面两个头文件)

用法:
    python aggregate_ipc.py --ipc-output-dir <dir>
"""

import argparse
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import List


def aggregate_ipc(ipc_output_dir: Path) -> int:
    """
    生成 IPC 汇总文件
    """
    proxy_dir = ipc_output_dir / "proxy"
    stub_dir = ipc_output_dir / "stub"

    # 查找所有 Proxy 和 Stub 文件
    proxy_files = sorted(proxy_dir.glob("*Proxy.h")) if proxy_dir.exists() else []
    stub_files = sorted(stub_dir.glob("*Stub.h")) if stub_dir.exists() else []

    if not proxy_files and not stub_files:
        print("No Proxy or Stub files found")
        return 0

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    # 生成 IpcAllProxies.h
    if proxy_files:
        lines = [
            "#if !defined(DAS_IPC_ALL_PROXIES_H)",
            "#define DAS_IPC_ALL_PROXIES_H",
            "",
            f"// Auto-generated at: {timestamp}",
            "// !!! DO NOT EDIT !!!",
            "",
        ]
        for f in proxy_files:
            lines.append(f'#include "proxy/{f.name}"')
        lines.extend(["", "#endif // DAS_IPC_ALL_PROXIES_H", ""])

        (ipc_output_dir / "IpcAllProxies.h").write_text("\n".join(lines), encoding="utf-8")
        print(f"Generated IpcAllProxies.h ({len(proxy_files)} proxies)")

    # 生成 IpcAllStubs.h
    if stub_files:
        lines = [
            "#if !defined(DAS_IPC_ALL_STUBS_H)",
            "#define DAS_IPC_ALL_STUBS_H",
            "",
            f"// Auto-generated at: {timestamp}",
            "// !!! DO NOT EDIT !!!",
            "",
        ]
        for f in stub_files:
            lines.append(f'#include "stub/{f.name}"')
        lines.extend(["", "#endif // DAS_IPC_ALL_STUBS_H", ""])

        (ipc_output_dir / "IpcAllStubs.h").write_text("\n".join(lines), encoding="utf-8")
        print(f"Generated IpcAllStubs.h ({len(stub_files)} stubs)")

    # 生成 IpcGenerated.cpp
    cpp_lines = [
        "// This file is automatically generated by DAS IDL Aggregator",
        f"// Generated at: {timestamp}",
        "// !!! DO NOT EDIT !!!",
        "//",
        "// IPC 代码编译入口 - include 所有生成的 Proxy 和 Stub 代码",
        "//",
        "",
    ]
    if proxy_files:
        cpp_lines.append('#include "IpcAllProxies.h"')
    if stub_files:
        cpp_lines.append('#include "IpcAllStubs.h"')
    cpp_lines.append("")

    (ipc_output_dir / "IpcGenerated.cpp").write_text("\n".join(cpp_lines), encoding="utf-8")
    print(f"Generated IpcGenerated.cpp")

    return 0


def main():
    parser = argparse.ArgumentParser(description='Aggregate IPC Proxy/Stub files')
    parser.add_argument('--ipc-output-dir', required=True, help='IPC output directory')
    args = parser.parse_args()

    ipc_output_dir = Path(args.ipc_output_dir)
    if not ipc_output_dir.exists():
        print(f"Error: Directory does not exist: {ipc_output_dir}", file=sys.stderr)
        return 1

    return aggregate_ipc(ipc_output_dir)


if __name__ == '__main__':
    sys.exit(main())
