#!/usr/bin/env python3
"""
DAS IDL Header Generator
Reads IDL files and generates C++ header files (.generated.h).

Usage:
    python das_header_generator.py --idl idl/DasResult.idl --output-dir build/gen/
    python das_header_generator.py --idl idl/DasCoreApi.idl --output-dir build/gen/ \
        --export-macro DAS_API --export-c-macro DAS_C_API
"""

import argparse
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from das_idl_parser import (
    ErrorCodeDef,
    ModuleDef,
    ModuleFunctionDef,
    ParameterDef,
    TypeInfo,
    parse_idl_file,
)


def _format_type(ti: TypeInfo) -> str:
    """Format a TypeInfo back to C++ type string."""
    result = ""
    if ti.is_const:
        result += "const "
    result += ti.base_type
    if ti.is_pointer:
        result += "*" * ti.pointer_level
    if ti.is_reference:
        result += "&"
    return result


def _format_params(params: list) -> str:
    """Format parameter list for function declaration."""
    parts = []
    for p in params:
        dir_prefix = ""
        if p.direction.value == "out":
            dir_prefix = "/* [out] */ "
        parts.append(f"{dir_prefix}{_format_type(p.type_info)} {p.name}")
    return ", ".join(parts)


def _format_return_type(ti: TypeInfo) -> str:
    """Format return type for function declaration."""
    return _format_type(ti)


def _das_ret_name(interface_name: str) -> str:
    """Derive DasRetXxx name from an interface type name.
    
    Strips namespace prefixes (Das::ExportInterface::, Das::PluginInterface::)
    and derives the Ret wrapper name.
    
    Examples:
        IDasBase -> DasRetIDasBase
        Das::ExportInterface::IDasImage -> DasRetIDasImage
        Das::PluginInterface::IPluginComponent -> DasRetIPluginComponent
    """
    short = interface_name.rsplit('::', 1)[-1]
    return f'DasRet{short}'


def _generate_ret_struct(interface_name: str) -> str:
    """Generate a DasRetXxx struct definition with include guard."""
    ret_name = _das_ret_name(interface_name)
    guard = f'DAS_RET_{interface_name.replace("::", "_").upper()}_DEFINED'
    return f"""\
#ifndef {guard}
#define {guard}
struct {ret_name} {{
    DasResult error_code{{DAS_E_UNDEFINED_RETURN_VALUE}};
    DAS::DasPtr<{interface_name}> value{{}};
    
    DasResult GetErrorCode() noexcept {{ return error_code; }}
    void SetErrorCode(DasResult in_error_code) noexcept {{ error_code = in_error_code; }}
    {interface_name}* GetValue() noexcept {{ return value.Get(); }}
    void SetValue({interface_name}* input_value) {{ value = input_value; }}
}};
#endif"""


def generate_header(
    doc,
    export_macro: str = "DAS_API",
    export_c_macro: str = "DAS_C_API",
    source_filename: str = "",
) -> str:
    """Generate a .generated.h string from an IdlDocument.

    Args:
        doc: Parsed IdlDocument from parse_idl_file().
        export_macro: Macro for [export] functions (default DAS_API).
        export_c_macro: Macro for [c_abi] functions (default DAS_C_API).
        source_filename: Original IDL filename for the header comment.

    Returns:
        Complete C++ header file content as a string.
    """
    lines = []

    # Header guard
    lines.append("#pragma once")
    lines.append("")

    # Generation comment
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines.append(f"// Generated by das_header_generator.py from {source_filename}")
    lines.append(f"// Generation time: {timestamp}")
    lines.append("// DO NOT EDIT - this file is auto-generated")
    lines.append("")

    # errorcode/defines → #define
    for ec in doc.error_codes:
        lines.append(f"// Constants: {ec.name}")
        for v in ec.values:
            lines.append(f"#define {v.name} {v.value}")
        lines.append("")

    # ── SWIG-compatible return wrappers ───────────────────────────────
    # For [export] (non-c_abi) functions with [out] parameters,
    # generate DasRetXxx structs and use them as return types.
    # This restores the SWIG-compatible API that was lost during
    # the dogfood migration from DasSwigApi.h to IDL.
    ret_types: set[str] = set()
    for mod in doc.modules:
        for func in mod.functions:
            if func.attributes.get('c_abi'):
                continue  # C ABI functions keep original signature
            for p in func.parameters:
                if p.direction.value == 'out':
                    ret_types.add(p.type_info.base_type)

    if ret_types:
        lines.append('// SWIG-compatible return wrappers')
        for iface_name in sorted(ret_types):
            lines.append(_generate_ret_struct(iface_name))
            lines.append('')
        lines.append('')

    # module → function declarations
    for mod in doc.modules:
        lines.append(f"// Module: {mod.name}")
        for func in mod.functions:
            if func.attributes.get("c_abi"):
                macro = export_c_macro
                params = _format_params(func.parameters)
                ret = _format_return_type(func.return_type)
            else:
                # [export] only: filter out [out] params → use DasRet return type
                macro = export_macro
                out_params = [p for p in func.parameters if p.direction.value == 'out']
                in_params = [p for p in func.parameters if p.direction.value != 'out']
                params = _format_params(in_params)
                if out_params:
                    # Use DasRetXxx as return type instead of DasResult + [out] ptr
                    ret = _das_ret_name(out_params[0].type_info.base_type)
                else:
                    ret = _format_return_type(func.return_type)
            lines.append(f"{macro} {ret} {func.name}({params});")
        lines.append("")

    # Remove trailing blank line
    if lines and lines[-1] == "":
        lines.pop()

    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(
        description="Generate C++ header files from DAS IDL files."
    )
    parser.add_argument(
        "--idl",
        required=True,
        help="Input IDL file path",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Output directory for generated headers",
    )
    parser.add_argument(
        "--export-macro",
        default="DAS_API",
        help="Export macro for [export] functions (default: DAS_API)",
    )
    parser.add_argument(
        "--export-c-macro",
        default="DAS_C_API",
        help="Export macro for [c_abi] functions (default: DAS_C_API)",
    )
    args = parser.parse_args()

    idl_path = Path(args.idl)
    output_dir = Path(args.output_dir)

    if not idl_path.exists():
        print(f"Error: IDL file not found: {idl_path}", file=sys.stderr)
        sys.exit(1)

    # Parse IDL file
    doc = parse_idl_file(str(idl_path))

    # Generate header content
    content = generate_header(
        doc,
        export_macro=args.export_macro,
        export_c_macro=args.export_c_macro,
        source_filename=idl_path.name,
    )

    # Write output
    output_dir.mkdir(parents=True, exist_ok=True)
    output_filename = f"{idl_path.stem}.generated.h"
    output_path = output_dir / output_filename
    output_path.write_text(content, encoding="utf-8")

    print(f"Generated: {output_path}")


if __name__ == "__main__":
    main()
