#!/usr/bin/env python3
"""
DAS IDL Header Generator
Reads IDL files and generates C++ header files (.generated.h).

Usage:
    python das_header_generator.py --idl idl/DasResult.idl --output-dir build/gen/
    python das_header_generator.py --idl idl/DasCoreApi.idl --output-dir build/gen/ \
        --export-macro DAS_API --export-c-macro DAS_C_API
"""

import argparse
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from das_idl_parser import (
    ErrorCodeDef,
    ModuleDef,
    ModuleFunctionDef,
    ParameterDef,
    TypeInfo,
    parse_idl_file,
)


def _format_type(ti: TypeInfo) -> str:
    """Format a TypeInfo back to C++ type string."""
    result = ""
    if ti.is_const:
        result += "const "
    result += ti.base_type
    if ti.is_pointer:
        result += "*" * ti.pointer_level
    if ti.is_reference:
        result += "&"
    return result


def _format_params(params: list) -> str:
    """Format parameter list for function declaration."""
    parts = []
    for p in params:
        dir_prefix = ""
        if p.direction.value == "out":
            dir_prefix = "/* [out] */ "
        parts.append(f"{dir_prefix}{_format_type(p.type_info)} {p.name}")
    return ", ".join(parts)


def _format_return_type(ti: TypeInfo) -> str:
    """Format return type for function declaration."""
    return _format_type(ti)


def generate_header(
    doc,
    export_macro: str = "DAS_API",
    export_c_macro: str = "DAS_C_API",
    source_filename: str = "",
) -> str:
    """Generate a .generated.h string from an IdlDocument.

    Args:
        doc: Parsed IdlDocument from parse_idl_file().
        export_macro: Macro for [export] functions (default DAS_API).
        export_c_macro: Macro for [c_abi] functions (default DAS_C_API).
        source_filename: Original IDL filename for the header comment.

    Returns:
        Complete C++ header file content as a string.
    """
    lines = []

    # Header guard
    lines.append("#pragma once")
    lines.append("")

    # Generation comment
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines.append(f"// Generated by das_header_generator.py from {source_filename}")
    lines.append(f"// Generation time: {timestamp}")
    lines.append("// DO NOT EDIT - this file is auto-generated")
    lines.append("")

    # errorcode → #define
    for ec in doc.error_codes:
        lines.append(f"// Error codes: {ec.name}")
        for v in ec.values:
            lines.append(f"#define {v.name} {v.value}")
        lines.append("")

    # module → function declarations
    for mod in doc.modules:
        lines.append(f"// Module: {mod.name}")
        for func in mod.functions:
            if func.attributes.get("c_abi"):
                macro = export_c_macro
            else:
                macro = export_macro
            params = _format_params(func.parameters)
            ret = _format_return_type(func.return_type)
            lines.append(f"{macro} {ret} {func.name}({params});")
        lines.append("")

    # Remove trailing blank line
    if lines and lines[-1] == "":
        lines.pop()

    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(
        description="Generate C++ header files from DAS IDL files."
    )
    parser.add_argument(
        "--idl",
        required=True,
        help="Input IDL file path",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Output directory for generated headers",
    )
    parser.add_argument(
        "--export-macro",
        default="DAS_API",
        help="Export macro for [export] functions (default: DAS_API)",
    )
    parser.add_argument(
        "--export-c-macro",
        default="DAS_C_API",
        help="Export macro for [c_abi] functions (default: DAS_C_API)",
    )
    args = parser.parse_args()

    idl_path = Path(args.idl)
    output_dir = Path(args.output_dir)

    if not idl_path.exists():
        print(f"Error: IDL file not found: {idl_path}", file=sys.stderr)
        sys.exit(1)

    # Parse IDL file
    doc = parse_idl_file(str(idl_path))

    # Generate header content
    content = generate_header(
        doc,
        export_macro=args.export_macro,
        export_c_macro=args.export_c_macro,
        source_filename=idl_path.name,
    )

    # Write output
    output_dir.mkdir(parents=True, exist_ok=True)
    output_filename = f"{idl_path.stem}.generated.h"
    output_path = output_dir / output_filename
    output_path.write_text(content, encoding="utf-8")

    print(f"Generated: {output_path}")


if __name__ == "__main__":
    main()
