#ifndef DAS_CORE_UTILS_STDEXECUTION_H
#define DAS_CORE_UTILS_STDEXECUTION_H

#include <das/DasConfig.h>

DAS_DISABLE_WARNING_BEGIN
DAS_IGNORE_STDEXEC_PARAMETERS

#include <stdexec/execution.hpp>

DAS_DISABLE_WARNING_END

#endif // DAS_CORE_UTILS_STDEXECUTION_H
