#include <das/DasConfig.h>
#include <das/DasString.hpp>
#include <das/IDasBase.h>

#include "IDasVariantVector.h"

DAS_DEFINE_RET_POINTER(
    DasRetIDasVariantVector,
    Das::ExportInterface::IDasVariantVector);

// DasRetIDasBase auto-generated by das_header_generator.py from DasCoreApi.idl
// [export] functions now live at global scope (no longer inside Das::Swig).
// DAS_SWIG_NS wrapper removed — downstream code should use unqualified names.

#include "DasCoreApi.generated.h"
