#ifndef DAS_CORE_IPC_IPC_ERRORS_H
#define DAS_CORE_IPC_IPC_ERRORS_H

#include <das/IDasBase.h>

// 之前的值比较容易冲突，这里搞大些避免冲突
#define DAS_E_IPC_BASE (-1080000000)

#define DAS_E_IPC_INVALID_MESSAGE_HEADER (DAS_E_IPC_BASE - 1)
#define DAS_E_IPC_INVALID_MESSAGE_TYPE (DAS_E_IPC_BASE - 2)
#define DAS_E_IPC_INVALID_MESSAGE_BODY (DAS_E_IPC_BASE - 3)
#define DAS_E_IPC_INVALID_OBJECT_ID (DAS_E_IPC_BASE - 4)
#define DAS_E_IPC_STALE_OBJECT_HANDLE (DAS_E_IPC_BASE - 5)
#define DAS_E_IPC_OBJECT_NOT_FOUND (DAS_E_IPC_BASE - 6)
#define DAS_E_IPC_TIMEOUT (DAS_E_IPC_BASE - 7)
#define DAS_E_IPC_CONNECTION_LOST (DAS_E_IPC_BASE - 8)
#define DAS_E_IPC_SHM_FAILED (DAS_E_IPC_BASE - 9)
#define DAS_E_IPC_MESSAGE_QUEUE_FAILED (DAS_E_IPC_BASE - 10)
#define DAS_E_IPC_INVALID_INTERFACE_ID (DAS_E_IPC_BASE - 11)
#define DAS_E_IPC_REMOTE_ERROR (DAS_E_IPC_BASE - 12)
#define DAS_E_IPC_DEADLOCK_DETECTED (DAS_E_IPC_BASE - 13)
#define DAS_E_IPC_SERIALIZATION_FAILED (DAS_E_IPC_BASE - 14)
#define DAS_E_IPC_DESERIALIZATION_FAILED (DAS_E_IPC_BASE - 15)
#define DAS_E_IPC_BUFFER_TOO_SMALL (DAS_E_IPC_BASE - 16)
#define DAS_E_IPC_INVALID_MESSAGE (DAS_E_IPC_BASE - 17)
#define DAS_E_IPC_CONNECTION_LIMIT_REACHED (DAS_E_IPC_BASE - 18)
#define DAS_E_IPC_INVALID_STATE (DAS_E_IPC_BASE - 19)
#define DAS_E_IPC_HANDSHAKE_FAILED (DAS_E_IPC_BASE - 20)

#endif // DAS_CORE_IPC_IPC_ERRORS_H
