import "DasBasicTypes.idl";

namespace Das::ExportInterface {

// 部分日志接口依赖该类型
[uuid("9BC34D72-E442-4944-ACE6-69257D262568")]
interface IDasSourceLocation {
    [get, set] IDasReadOnlyString FileName;
    [get, set] int32_t Line;
    [get, set] IDasReadOnlyString FunctionName;
};

[uuid("F4191604-D061-49A4-85EC-28EFC376119F")]
interface IDasLogReader : IDasBase {
    DasResult ReadOne(IDasReadOnlyString* message);
}

[uuid("806E244C-CCF0-4DC3-AD54-6886FDF9B1F4")]
interface IDasLogRequester : IDasBase {
    /**
     * @brief 使用用户自定义的方法对数据进行读取
     * @param p_reader 在内部加锁后进行阅读的操作，由用户继承并实现
     * @return 指示操作是否成功
     */
    DasResult RequestOne(IDasLogReader* p_reader);
}

}