errorcode DasResult {
    DAS_S_OK = 0,
    DAS_S_FALSE = 1,
    DAS_E_RESERVED = -1073750000,
    DAS_E_NO_INTERFACE = -1073750001,
    DAS_E_UNDEFINED_RETURN_VALUE = -1073750002,
    DAS_E_INVALID_STRING = -1073750003,
    DAS_E_INVALID_STRING_SIZE = -1073750004,
    DAS_E_NO_IMPLEMENTATION = -1073750005,
    DAS_E_UNSUPPORTED_SYSTEM = -1073750006,
    DAS_E_INVALID_JSON = -1073750007,
    DAS_E_TYPE_ERROR = -1073750008,
    DAS_E_INVALID_FILE = -1073750009,
    DAS_E_INVALID_URL = -1073750010,
    DAS_E_OUT_OF_RANGE = -1073750011,
    DAS_E_DUPLICATE_ELEMENT = -1073750012,
    DAS_E_FILE_NOT_FOUND = -1073750013,
    DAS_E_MAYBE_OVERFLOW = -1073750014,
    DAS_E_OUT_OF_MEMORY = -1073750015,
    DAS_E_INVALID_PATH = -1073750016,
    DAS_E_INVALID_POINTER = -1073750017,
    DAS_E_SWIG_INTERNAL_ERROR = -1073750018,
    DAS_E_PYTHON_ERROR = -1073750019,
    DAS_E_JAVA_ERROR = -1073750020,
    DAS_E_CSHARP_ERROR = -1073750021,
    DAS_E_INTERNAL_FATAL_ERROR = -1073750022,
    DAS_E_INVALID_ENUM = -1073750023,
    DAS_E_INVALID_SIZE = -1073750024,
    DAS_E_OPENCV_ERROR = -1073750025,
    DAS_E_ONNX_RUNTIME_ERROR = -1073750026,
    DAS_E_TIMEOUT = -1073750027,
    DAS_E_ACCESS_DENIED = -1073750029,
    DAS_E_SYMBOL_NOT_FOUND = -1073750030,
    DAS_E_DANGLING_REFERENCE = -1073750031,
    DAS_E_OBJECT_NOT_INIT = -1073750032,
    DAS_E_UNEXPECTED_THREAD_DETECTED = -1073750033,
    DAS_E_STRONG_REFERENCE_NOT_AVAILABLE = -1073750034,
    DAS_E_TASK_WORKING = -1073750035,
    DAS_E_OBJECT_ALREADY_INIT = -1073750036,
    DAS_E_FAIL = -1073750037,
    DAS_E_INVALID_ARGUMENT = -1073750038,
    DAS_E_CAPTURE_FAILED = -1073750039,
    DAS_E_NOT_FOUND = -1073750040,
    DAS_E_IPC_UNKNOWN_METHOD = -1073750041,
    DAS_E_JAVASCRIPT_ERROR = -1073750042,
    DAS_E_JAVASCRIPT_NO_IMPLEMENTATION = -1073750043,
    DAS_E_CSHARP_MISSING_RUNTIMECONFIG = -1073750044,
    DAS_E_CSHARP_UNSUPPORTED_TFM = -1073750045,
    DAS_E_CSHARP_HOSTFXR_INIT_FAILED = -1073750046,
    DAS_E_CSHARP_COM_CLR_INIT_FAILED = -1073750047,
    DAS_E_CSHARP_ENTRYPOINT_MISSING = -1073750048,
    DAS_E_CSHARP_PLUGIN_INIT_FAILED = -1073750049,
    DAS_E_CSHARP_MANIFEST_INVALID = -1073800000,
    DAS_E_CSHARP_ENTRYPOINT_INVALID = -1073800001,
    DAS_E_CSHARP_BOOTSTRAP_INVALID = -1073800002,
    DAS_E_CSHARP_DIRECTOR_FACTORY_FAILED = -1073800003,
    DAS_E_CSHARP_NETFX_UNSUPPORTED_PLATFORM = -1073800004,
}
