import "DasBasicTypes.idl";
import "DasJson.idl";

namespace Das::ExportInterface {

// Phase 41 removed: IDasJsonSettingOnDeletedHandler, IDasJsonSettingOperator, IDasJsonSetting

enum DasProfileProperty {
    DAS_PROFILE_PROPERTY_PROFILE = 0,
    DAS_PROFILE_PROPERTY_SCHEDULER_STATE = 1,
    DAS_PROFILE_PROPERTY_NAME = 1001,
    DAS_PROFILE_PROPERTY_ID = 1002,
    DAS_PROFILE_PROPERTY_FORCE_DWORD = 0x7FFFFFFF
}

[uuid("8A7B3D5E-1F2A-4C6D-9E8B-3A4F5D6C7B8E")]
interface IDasProfileService : IDasBase {
    DasResult GetProfile(const DasGuid& plugin_guid, [out] IDasPluginProfile** pp_out);
}

[uuid("2D4E6F8A-3B5C-4D7E-A1C2-E3F4A5B6C7D8")]
interface IDasPluginProfile : IDasBase {
    DasResult GetSettingJson([out] IDasJson** pp_out);
}

}