import "DasBasicTypes.idl";
import "DasJson.idl";

namespace Das::ExportInterface {

// Phase 41: IDasJsonSettingOnDeletedHandler, IDasJsonSettingOperator, IDasJsonSetting removed.
// SettingsManager now uses nlohmann::json directly in the main process.
// IDasProfile will be restored in Phase 43.

enum DasProfileProperty {
    DAS_PROFILE_PROPERTY_PROFILE = 0,
    DAS_PROFILE_PROPERTY_SCHEDULER_STATE = 1,
    DAS_PROFILE_PROPERTY_NAME = 1001,
    DAS_PROFILE_PROPERTY_ID = 1002,
    DAS_PROFILE_PROPERTY_FORCE_DWORD = 0x7FFFFFFF
}

// Phase 43 will restore and update IDasProfile with new method signatures.
// [uuid("774869F9-B453-4CA5-8512-B08E659383EA")]
// interface IDasProfile : IDasBase {
//     DasResult GetStringProperty(DasProfileProperty profile_property, [out] IDasReadOnlyString** pp_out_property);
//     DasResult GetJsonSettingPropertyAsString(DasProfileProperty profile_property, [out] IDasReadOnlyString** pp_out_string);
// }

}