import "DasBasicTypes.idl";
import "IDasBinaryBuffer.idl";

namespace Das::ExportInterface {

[uuid("0E8E6129-512E-4AAB-A4A6-327ADCACB019")]
interface IDasMemory : IDasBase {
    /**
     * @brief 获取二进制缓冲区对象
     * @note 此方法替代了原来的 GetRawData 方法
     *       提供更安全的二进制数据访问方式
     *       SWIG: 提供目标语言友好的访问方法
     */
    DasResult GetBinaryBuffer([out, ref] IDasBinaryBuffer* p_out_buffer);

    /**
     * @brief 如果确定输入的指针不是空指针，则返回值可以忽略
     */
    DasResult GetSize([out] uint64_t* p_out_size);
    DasResult GetOffset([out] int64_t* p_out_offset);
    DasResult SetOffset(int64_t offset);
    DasResult Resize(uint64_t new_size_in_byte);
}

}
