import "DasBasicTypes.idl";
import "IDasTask.idl";

namespace Das::ExportInterface
{
    [uuid("E8B7A3D1-4F2C-4A1E-9D5B-8C6E7F3A2B1D")] interface IDasGraphRuntime
        : IDasBase
    {
        /// Get last error message (valid for the lifetime of this object).
        DasResult
            GetErrorMessage([out] IDasReadOnlyString * *pp_out_error_message);
    }
}
