import "DasBasicTypes.idl";
import "DasJson.idl";
import "IDasTypeInfo.idl";
import "IDasTask.idl";

namespace Das::PluginInterface
{

    [uuid("A64B5521-F58C-4231-A7D3-2E167D4DD3B2")] interface IDasTaskComponent
        : IDasTypeInfo
    {
        DasResult ApplySettingsChange(
            Das::ExportInterface::IDasJson * p_request_json,
            [out] Das::ExportInterface::IDasJson ** pp_out_result_json);
        DasResult Do(
            IDasStopToken * stop_token,
            Das::ExportInterface::IDasJson * p_environment_json,
            Das::ExportInterface::IDasJson * p_settings_json,
            Das::ExportInterface::IDasJson * p_input_json,
            [out] Das::ExportInterface::IDasJson ** pp_out_result_json);
    }

    [uuid("630BB8E7-B2D5-4D1C-9AD8-A0D34E07A270")] interface IDasTaskComponentFactory
        : IDasTypeInfo
    {
        DasResult CreateComponent(
            const DasGuid & component_guid,
            [out] IDasTaskComponent ** pp_out_component);
    }

}
