import "DasBasicTypes.idl";
import "DasJson.idl";

namespace Das::PluginInterface
{

    [uuid("0A07F5B0-63CB-4D77-9D41-786C2A602527")] interface IDasTaskAuthoringSession
        : IDasBase
    {
        DasResult GetDocument(
            Das::ExportInterface::IDasJson * p_request_json,
            [out] Das::ExportInterface::IDasJson ** pp_out_document_json);
        DasResult ApplyChange(
            Das::ExportInterface::IDasJson * p_request_json,
            [out] Das::ExportInterface::IDasJson ** pp_out_result_json);
        DasResult Compile(
            Das::ExportInterface::IDasJson * p_request_json,
            [out] Das::ExportInterface::IDasJson ** pp_out_result_json);
    }

    [uuid("B91C3145-6E11-45E4-876E-1155C13D5E6C")] interface IDasTaskAuthoringSessionFactory
        : IDasBase
    {
        DasResult CreateSession(
            const DasGuid & task_guid,
            Das::ExportInterface::IDasJson * p_context_json,
            [out] IDasTaskAuthoringSession ** pp_out_session);
    }

}
