import "DasBasicTypes.idl";
import "DasJson.idl";
import "IDasTask.idl";
import "IDasTaskComponent.idl";

namespace Das::ExportInterface
{
    [uuid("E8B7A3D1-4F2C-4A1E-9D5B-8C6E7F3A2B1D")] interface IDasGraphRuntime
        : IDasBase
    {
        /// Get last error message (valid for the lifetime of this object).
        DasResult
            GetErrorMessage([out] IDasReadOnlyString * *pp_out_error_message);

        /// Execute a compiled graph plan.
        /// The host for component resolution is bound at construction time.
        DasResult Execute(
            IDasReadOnlyString * p_compiled_artifact_json,
            Das::PluginInterface::IDasStopToken * p_stop_token,
            [out] Das::ExportInterface::IDasJson * *pp_out_result_json);
    }
}
