# CMake脚本：生成汇总所有SWIG接口的_all.i文件
# 用法：cmake -DSWIG_OUTPUT_DIR=... -DABI_OUTPUT_DIR=... -P generate_swig_all_i.cmake

# 获取当前时间
string(TIMESTAMP CURRENT_TIME "%Y-%m-%d %H:%M:%S UTC" UTC)

# 设置_all.i文件输出路径（在SWIG输出目录根目录下）
set(ALL_I_FILE "${SWIG_OUTPUT_DIR}/swig_all.i")

# 开始生成_all.i文件
file(WRITE ${ALL_I_FILE} "// This file is automatically generated by CMake\n")
file(APPEND ${ALL_I_FILE} "// Generated at: ${CURRENT_TIME}\n")
file(APPEND ${ALL_I_FILE} "// !!! DO NOT EDIT !!!\n\n")
file(APPEND ${ALL_I_FILE} "// Master SWIG interface file - includes all generated SWIG interfaces\n\n")

# 遍历SWIG输出目录下的所有.i文件
file(GLOB SWIG_I_FILES "${SWIG_OUTPUT_DIR}/*.i")

if(SWIG_I_FILES)
    foreach(I_FILE ${SWIG_I_FILES})
        get_filename_component(I_FILENAME ${I_FILE} NAME_WE)
        
        # 排除_all.i文件本身
        if(NOT "${I_FILENAME}" MATCHES "_all$")
            # 尝试从文件名中提取IDL名称
            # 假设文件名格式为: *.IDL名称*.i
            # 提取最后一个句号之前的部分作为IDL名称
            string(REGEX REPLACE ".*\\.([^.]*)$" "\\1" IDL_NAME "${I_FILENAME}")
            
            # 如果提取不到，使用整个文件名
            if("${IDL_NAME}" STREQUAL "${I_FILENAME}")
                set(IDL_NAME "${I_FILENAME}")
            endif()
            
            # 查找对应的ABI头文件（在ABI输出目录根目录下）
            set(HEADER_FILE "${ABI_OUTPUT_DIR}/${IDL_NAME}.h")
            if(EXISTS ${HEADER_FILE})
                file(APPEND ${ALL_I_FILE} "%{\n")
                file(APPEND ${ALL_I_FILE} "// ABI Header file for ${IDL_NAME}\n")
                file(APPEND ${ALL_I_FILE} "#include \"${IDL_NAME}.h\"\n")
                file(APPEND ${ALL_I_FILE} "%}\n\n")
            endif()
            
            # 包含该.i文件
            file(APPEND ${ALL_I_FILE} "%include \"${I_FILENAME}.i\"\n\n")
        endif()
    endforeach()
endif()

message(STATUS "Generated summary SWIG all.i file: ${ALL_I_FILE}")
