# CMake脚本：生成汇总所有SWIG接口的_all.i文件
# 用法：cmake -DSWIG_OUTPUT_DIR=... -DABI_OUTPUT_DIR=... -P generate_swig_all_i.cmake

# 获取当前时间
string(TIMESTAMP CURRENT_TIME "%Y-%m-%d %H:%M:%S UTC" UTC)

# 设置_all.i文件输出路径（在SWIG输出目录根目录下）
set(ALL_I_FILE "${SWIG_OUTPUT_DIR}/swig_all.i")

# 开始生成_all.i文件
file(WRITE ${ALL_I_FILE} "// This file is automatically generated by CMake\n")
file(APPEND ${ALL_I_FILE} "// Generated at: ${CURRENT_TIME}\n")
file(APPEND ${ALL_I_FILE} "// !!! DO NOT EDIT !!!\n\n")
file(APPEND ${ALL_I_FILE} "// Master SWIG interface file - includes all generated SWIG interfaces\n\n")

# 遍历SWIG输出目录下的所有.i文件
file(GLOB SWIG_I_FILES "${SWIG_OUTPUT_DIR}/*.i")

if(SWIG_I_FILES)
    foreach(I_FILE ${SWIG_I_FILES})
        get_filename_component(I_FILENAME ${I_FILE} NAME_WE)

        # 排除_all.i文件本身
        if(NOT "${I_FILENAME}" MATCHES "_all$")
            # 每个SWIG .i 文件已经自己包含了所需的ABI头文件
            # 这里直接包含 .i 文件即可
            file(APPEND ${ALL_I_FILE} "%include \"${I_FILENAME}.i\"\n\n")
        endif()
    endforeach()
endif()

message(STATUS "Generated summary SWIG all.i file: ${ALL_I_FILE}")
