# CMake脚本：生成汇总所有SWIG接口的_all.i文件
# 用法：cmake -DSWIG_OUTPUT_DIR=... -DABI_OUTPUT_DIR=... -P generate_swig_all_i.cmake

# 获取当前时间
string(TIMESTAMP CURRENT_TIME "%Y-%m-%d %H:%M:%S UTC" UTC)

# 设置_all.i文件输出路径（在SWIG输出目录根目录下）
set(ALL_I_FILE "${SWIG_OUTPUT_DIR}/swig_all.i")

# 开始生成_all.i文件
file(WRITE ${ALL_I_FILE} "// This file is automatically generated by CMake\n")
file(APPEND ${ALL_I_FILE} "// Generated at: ${CURRENT_TIME}\n")
file(APPEND ${ALL_I_FILE} "// !!! DO NOT EDIT !!!\n\n")
file(APPEND ${ALL_I_FILE} "// Master SWIG interface file - includes all generated SWIG interfaces\n\n")

# 读取sorted_interfaces.txt获取按依赖关系排序的接口列表
set(SORTED_INTERFACES_FILE "${CMAKE_CURRENT_LIST_DIR}/../sorted_interfaces.txt")

# 检查sorted_interfaces.txt是否存在
if(NOT EXISTS "${SORTED_INTERFACES_FILE}")
    message(FATAL_ERROR "sorted_interfaces.txt not found at: ${SORTED_INTERFACES_FILE}")
endif()

# 读取排序后的接口列表
file(STRINGS "${SORTED_INTERFACES_FILE}" INTERFACE_LIST)

# 按排序顺序处理接口
foreach(INTERFACE_NAME ${INTERFACE_LIST})
    # 跳过空行
    if("${INTERFACE_NAME}" STREQUAL "")
        continue()
    endif()

    # 排除_all.i文件本身（虽然sorted_interfaces.txt中应该不会包含）
    if(NOT "${INTERFACE_NAME}" MATCHES "_all$")
        # 检查对应的 .i 文件是否存在
        set(INTERFACE_I_FILE "${SWIG_OUTPUT_DIR}/${INTERFACE_NAME}.i")
        if(EXISTS "${INTERFACE_I_FILE}")
            # 每个SWIG .i 文件已经自己包含了所需的ABI头文件
            # 这里直接包含 .i 文件即可
            file(APPEND ${ALL_I_FILE} "%include \"${INTERFACE_NAME}.i\"\n\n")
        else()
            message(STATUS "Skipping ${INTERFACE_NAME} (no .i file found)")
        endif()
    endif()
endforeach()

# ====== 生成DasTypeMaps.i（汇总所有typemap） ======
message(STATUS "Aggregating typemaps to DasTypeMaps.i...")

# 查找所有typemap_info_*.json文件（在SWIG输出目录中）
file(GLOB TYPEMAP_JSON_FILES "${SWIG_OUTPUT_DIR}/typemap_info_*.json")

 # 检查是否有typemap_info文件
 if(TYPEMAP_JSON_FILES)
     message(STATUS "Found ${TYPEMAP_JSON_FILES} typemap_info JSON files")

    # 将CMake列表转换为Python列表字符串
    # 注意：需要正确处理Windows路径中的反斜杠
    string(REPLACE ";" "','" PYTHON_JSON_LIST "'${TYPEMAP_JSON_FILES}'")

    # 获取CMake脚本的目录（cmake/generate_swig_all_i.cmake）
    # CMAKE_CURRENT_LIST_DIR指向脚本所在目录
    get_filename_component(DAS_ROOT_DIR "${CMAKE_CURRENT_LIST_DIR}" DIRECTORY)

    # 调用Python脚本汇总typemap到DasTypeMaps.i
    # 注意：在cmake -P脚本模式下，使用Python的-c参数直接调用函数
    # Python会使用generate_type_maps_from_jsons函数中的SOURCE_DIR来处理输出路径
    execute_process(
        COMMAND ${Python3_EXECUTABLE} -c
            "import sys, ast; sys.path.insert(0, '${DAS_ROOT_DIR}/tools/das_idl'); from das_idl_gen import generate_type_maps_from_jsons; json_files = ast.literal_eval('''[${PYTHON_JSON_LIST}]'''); result = generate_type_maps_from_jsons(json_files, 'SWIG/DasTypeMaps.i'); print(f'STDOUT: {result}'); sys.exit(0 if result is None else 1)"
        RESULT_VARIABLE PYTHON_RESULT
        OUTPUT_VARIABLE PYTHON_OUTPUT
        ERROR_VARIABLE PYTHON_ERROR
    )
 
    if(NOT PYTHON_RESULT EQUAL 0)
        message(FATAL_ERROR "Failed to aggregate typemaps: ${PYTHON_ERROR}")
    else()
        message(STATUS "${PYTHON_OUTPUT}")
    endif()
else()
    message(STATUS "No typemap_info JSON files found, skipping DasTypeMaps.i generation")
endif()

message(STATUS "Generated summary SWIG all.i file: ${ALL_I_FILE}")
